// lib/surahData.ts

export const SURAH_LIST = [
  { id: 1, name: "Al-Fatiha", total: 7 },
  { id: 2, name: "Al-Baqarah", total: 286 },
  { id: 3, name: "Ali 'Imran", total: 200 },
  { id: 4, name: "An-Nisa", total: 176 },
  { id: 5, name: "Al-Ma'idah", total: 120 },
  { id: 6, name: "Al-An'am", total: 165 },
  { id: 7, name: "Al-A'raf", total: 206 },
  { id: 8, name: "Al-Anfal", total: 75 },
  { id: 9, name: "At-Tawbah", total: 129 },
  { id: 10, name: "Yunus", total: 109 },
  { id: 11, name: "Hud", total: 123 },
  { id: 12, name: "Yusuf", total: 111 },
  { id: 13, name: "Ar-Ra'd", total: 43 },
  { id: 14, name: "Ibrahim", total: 52 },
  { id: 15, name: "Al-Hijr", total: 99 },
  { id: 16, name: "An-Nahl", total: 128 },
  { id: 17, name: "Al-Isra", total: 111 },
  { id: 18, name: "Al-Kahf", total: 110 },
  { id: 19, name: "Maryam", total: 98 },
  { id: 20, name: "Ta-Ha", total: 135 },
  { id: 21, name: "Al-Anbya", total: 112 },
  { id: 22, name: "Al-Hajj", total: 78 },
  { id: 23, name: "Al-Mu'minun", total: 118 },
  { id: 24, name: "An-Nur", total: 64 },
  { id: 25, name: "Al-Furqan", total: 77 },
  { id: 26, name: "Ash-Shu'ara", total: 227 },
  { id: 27, name: "An-Naml", total: 93 },
  { id: 28, name: "Al-Qasas", total: 88 },
  { id: 29, name: "Al-Ankabut", total: 69 },
  { id: 30, name: "Ar-Rum", total: 60 },
  { id: 31, name: "Luqman", total: 34 },
  { id: 32, name: "As-Sajdah", total: 30 },
  { id: 33, name: "Al-Ahzab", total: 73 },
  { id: 34, name: "Saba", total: 54 },
  { id: 35, name: "Fatir", total: 45 },
  { id: 36, name: "Ya-Sin", total: 83 },
  { id: 37, name: "As-Saffat", total: 182 },
  { id: 38, name: "Sad", total: 88 },
  { id: 39, name: "Az-Zumar", total: 75 },
  { id: 40, name: "Ghafir", total: 85 },
  { id: 41, name: "Fussilat", total: 54 },
  { id: 42, name: "Ash-Shura", total: 53 },
  { id: 43, name: "Az-Zukhruf", total: 89 },
  { id: 44, name: "Ad-Dukhan", total: 59 },
  { id: 45, name: "Al-Jathiyah", total: 37 },
  { id: 46, name: "Al-Ahqaf", total: 35 },
  { id: 47, name: "Muhammad", total: 38 },
  { id: 48, name: "Al-Fath", total: 29 },
  { id: 49, name: "Al-Hujurat", total: 18 },
  { id: 50, name: "Qaf", total: 45 },
  { id: 51, name: "Ad-Dhariyat", total: 60 },
  { id: 52, name: "At-Tur", total: 49 },
  { id: 53, name: "An-Najm", total: 62 },
  { id: 54, name: "Al-Qamar", total: 55 },
  { id: 55, name: "Ar-Rahman", total: 78 },
  { id: 56, name: "Al-Waqi'ah", total: 96 },
  { id: 57, name: "Al-Hadid", total: 29 },
  { id: 58, name: "Al-Mujadila", total: 22 },
  { id: 59, name: "Al-Hashr", total: 24 },
  { id: 60, name: "Al-Mumtahanah", total: 13 },
  { id: 61, name: "As-Saff", total: 14 },
  { id: 62, name: "Al-Jumu'ah", total: 11 },
  { id: 63, name: "Al-Munafiqun", total: 11 },
  { id: 64, name: "At-Taghabun", total: 18 },
  { id: 65, name: "At-Talaq", total: 12 },
  { id: 66, name: "At-Tahrim", total: 12 },
  { id: 67, name: "Al-Mulk", total: 30 },
  { id: 68, name: "Al-Qalam", total: 52 },
  { id: 69, name: "Al-Haqqah", total: 52 },
  { id: 70, name: "Al-Ma'arij", total: 44 },
  { id: 71, name: "Nuh", total: 28 },
  { id: 72, name: "Al-Jinn", total: 28 },
  { id: 73, name: "Al-Muzzammil", total: 20 },
  { id: 74, name: "Al-Muddaththir", total: 56 },
  { id: 75, name: "Al-Qiyamah", total: 40 },
  { id: 76, name: "Al-Insan", total: 31 },
  { id: 77, name: "Al-Mursalat", total: 50 },
  { id: 78, name: "An-Naba", total: 40 },
  { id: 79, name: "An-Nazi'at", total: 46 },
  { id: 80, name: "Abasa", total: 42 },
  { id: 81, name: "At-Takwir", total: 29 },
  { id: 82, name: "Al-Infitar", total: 19 },
  { id: 83, name: "Al-Mutaffifin", total: 36 },
  { id: 84, name: "Al-Inshiqaq", total: 25 },
  { id: 85, name: "Al-Buruj", total: 22 },
  { id: 86, name: "At-Tariq", total: 17 },
  { id: 87, name: "Al-A'la", total: 19 },
  { id: 88, name: "Al-Ghashiyah", total: 26 },
  { id: 89, name: "Al-Fajr", total: 30 },
  { id: 90, name: "Al-Balad", total: 20 },
  { id: 91, name: "Ash-Shams", total: 15 },
  { id: 92, name: "Al-Layl", total: 21 },
  { id: 93, name: "Ad-Duhaa", total: 11 },
  { id: 94, name: "Ash-Sharh", total: 8 },
  { id: 95, name: "At-Tin", total: 8 },
  { id: 96, name: "Al-Alaq", total: 19 },
  { id: 97, name: "Al-Qadr", total: 5 },
  { id: 98, name: "Al-Bayyinah", total: 8 },
  { id: 99, name: "Az-Zalzalah", total: 8 },
  { id: 100, name: "Al-Adiyat", total: 11 },
  { id: 101, name: "Al-Qari'ah", total: 11 },
  { id: 102, name: "At-Takathur", total: 8 },
  { id: 103, name: "Al-Asr", total: 3 },
  { id: 104, name: "Al-Humazah", total: 9 },
  { id: 105, name: "Al-Fil", total: 5 },
  { id: 106, name: "Quraysh", total: 4 },
  { id: 107, name: "Al-Ma'un", total: 7 },
  { id: 108, name: "Al-Kawthar", total: 3 },
  { id: 109, name: "Al-Kafirun", total: 6 },
  { id: 110, name: "An-Nasr", total: 3 },
  { id: 111, name: "Al-Masad", total: 5 },
  { id: 112, name: "Al-Ikhlas", total: 4 },
  { id: 113, name: "Al-Falaq", total: 5 },
  { id: 114, name: "An-Nas", total: 6 },
];

export function getSurahName(id: number) {
  return SURAH_LIST.find((s) => s.id === id)?.name || `Surah ${id}`;
}

export function getTotalVerses(id: number) {
  return SURAH_LIST.find((s) => s.id === id)?.total || 30;
}
